package com.escapelog.escapelog.domain;

public enum AreaType {
    SEUOL, GYEONGGI, INCHEON, GANGWON, CHUNGCHEONGBUK,
    CHUNGCHEONGNAM, DAEJEON, JEOLLABUK, JEOLLANAM, GWANGJU,
    GYEONGSANGBUK, GYEONGSANGNAM, DEAGU, BUSAN, JEJU
}
